/**
 * Gentilés français par pays (ISO 3166-1 alpha-2), au masculin et au féminin.
 *
 * La nationalité est stockée par son CODE pays : c'est stable et indépendant de
 * la langue. Mais un dossier RH ne s'écrit pas « SN » — il s'écrit
 * « Sénégalaise ». Cette table fait la traduction, et l'accord, parce que le
 * français ne le devine pas : Grec/Grecque et Turc/Turque ne se dérivent pas
 * d'une règle.
 *
 * Partagée avec le serveur : l'attestation de travail et les descriptions de
 * demandes de correction en ont besoin autant que l'interface.
 */

/** [masculin, féminin] — identiques quand le gentilé est invariable. */
export const DEMONYMS: Record<string, readonly [string, string]> = {
  AF: ['Afghan', 'Afghane'],
  ZA: ['Sud-Africain', 'Sud-Africaine'],
  AL: ['Albanais', 'Albanaise'],
  DZ: ['Algérien', 'Algérienne'],
  DE: ['Allemand', 'Allemande'],
  AD: ['Andorran', 'Andorrane'],
  AO: ['Angolais', 'Angolaise'],
  AG: ['Antiguais', 'Antiguaise'],
  SA: ['Saoudien', 'Saoudienne'],
  AR: ['Argentin', 'Argentine'],
  AM: ['Arménien', 'Arménienne'],
  AU: ['Australien', 'Australienne'],
  AT: ['Autrichien', 'Autrichienne'],
  AZ: ['Azerbaïdjanais', 'Azerbaïdjanaise'],
  BS: ['Bahaméen', 'Bahaméenne'],
  BH: ['Bahreïnien', 'Bahreïnienne'],
  BD: ['Bangladais', 'Bangladaise'],
  BB: ['Barbadien', 'Barbadienne'],
  BE: ['Belge', 'Belge'],
  BZ: ['Bélizien', 'Bélizienne'],
  BJ: ['Béninois', 'Béninoise'],
  BT: ['Bhoutanais', 'Bhoutanaise'],
  BY: ['Biélorusse', 'Biélorusse'],
  BO: ['Bolivien', 'Bolivienne'],
  BA: ['Bosnien', 'Bosnienne'],
  BW: ['Botswanais', 'Botswanaise'],
  BR: ['Brésilien', 'Brésilienne'],
  BN: ['Brunéien', 'Brunéienne'],
  BG: ['Bulgare', 'Bulgare'],
  BF: ['Burkinabè', 'Burkinabè'],
  BI: ['Burundais', 'Burundaise'],
  KH: ['Cambodgien', 'Cambodgienne'],
  CM: ['Camerounais', 'Camerounaise'],
  CA: ['Canadien', 'Canadienne'],
  CV: ['Cap-Verdien', 'Cap-Verdienne'],
  CL: ['Chilien', 'Chilienne'],
  CN: ['Chinois', 'Chinoise'],
  CY: ['Chypriote', 'Chypriote'],
  CO: ['Colombien', 'Colombienne'],
  KM: ['Comorien', 'Comorienne'],
  CG: ['Congolais', 'Congolaise'],
  CD: ['Congolais', 'Congolaise'],
  KR: ['Sud-Coréen', 'Sud-Coréenne'],
  KP: ['Nord-Coréen', 'Nord-Coréenne'],
  CR: ['Costaricien', 'Costaricienne'],
  CI: ['Ivoirien', 'Ivoirienne'],
  HR: ['Croate', 'Croate'],
  CU: ['Cubain', 'Cubaine'],
  DK: ['Danois', 'Danoise'],
  DJ: ['Djiboutien', 'Djiboutienne'],
  DM: ['Dominiquais', 'Dominiquaise'],
  EG: ['Égyptien', 'Égyptienne'],
  AE: ['Émirien', 'Émirienne'],
  EC: ['Équatorien', 'Équatorienne'],
  ER: ['Érythréen', 'Érythréenne'],
  ES: ['Espagnol', 'Espagnole'],
  EE: ['Estonien', 'Estonienne'],
  SZ: ['Swazi', 'Swazie'],
  US: ['Américain', 'Américaine'],
  ET: ['Éthiopien', 'Éthiopienne'],
  FJ: ['Fidjien', 'Fidjienne'],
  FI: ['Finlandais', 'Finlandaise'],
  FR: ['Français', 'Française'],
  GA: ['Gabonais', 'Gabonaise'],
  GM: ['Gambien', 'Gambienne'],
  GE: ['Géorgien', 'Géorgienne'],
  GH: ['Ghanéen', 'Ghanéenne'],
  GR: ['Grec', 'Grecque'],
  GD: ['Grenadien', 'Grenadienne'],
  GT: ['Guatémaltèque', 'Guatémaltèque'],
  GN: ['Guinéen', 'Guinéenne'],
  GW: ['Bissau-Guinéen', 'Bissau-Guinéenne'],
  GQ: ['Équato-Guinéen', 'Équato-Guinéenne'],
  GY: ['Guyanien', 'Guyanienne'],
  HT: ['Haïtien', 'Haïtienne'],
  HN: ['Hondurien', 'Hondurienne'],
  HU: ['Hongrois', 'Hongroise'],
  IN: ['Indien', 'Indienne'],
  ID: ['Indonésien', 'Indonésienne'],
  IQ: ['Irakien', 'Irakienne'],
  IR: ['Iranien', 'Iranienne'],
  IE: ['Irlandais', 'Irlandaise'],
  IS: ['Islandais', 'Islandaise'],
  IL: ['Israélien', 'Israélienne'],
  IT: ['Italien', 'Italienne'],
  JM: ['Jamaïcain', 'Jamaïcaine'],
  JP: ['Japonais', 'Japonaise'],
  JO: ['Jordanien', 'Jordanienne'],
  KZ: ['Kazakh', 'Kazakhe'],
  KE: ['Kényan', 'Kényane'],
  KG: ['Kirghize', 'Kirghize'],
  KI: ['Kiribatien', 'Kiribatienne'],
  KW: ['Koweïtien', 'Koweïtienne'],
  LA: ['Laotien', 'Laotienne'],
  LS: ['Lesothan', 'Lesothane'],
  LV: ['Letton', 'Lettone'],
  LB: ['Libanais', 'Libanaise'],
  LR: ['Libérien', 'Libérienne'],
  LY: ['Libyen', 'Libyenne'],
  LI: ['Liechtensteinois', 'Liechtensteinoise'],
  LT: ['Lituanien', 'Lituanienne'],
  LU: ['Luxembourgeois', 'Luxembourgeoise'],
  MK: ['Macédonien', 'Macédonienne'],
  MG: ['Malgache', 'Malgache'],
  MY: ['Malaisien', 'Malaisienne'],
  MW: ['Malawien', 'Malawienne'],
  MV: ['Maldivien', 'Maldivienne'],
  ML: ['Malien', 'Malienne'],
  MT: ['Maltais', 'Maltaise'],
  MA: ['Marocain', 'Marocaine'],
  MH: ['Marshallais', 'Marshallaise'],
  MU: ['Mauricien', 'Mauricienne'],
  MR: ['Mauritanien', 'Mauritanienne'],
  MX: ['Mexicain', 'Mexicaine'],
  FM: ['Micronésien', 'Micronésienne'],
  MD: ['Moldave', 'Moldave'],
  MC: ['Monégasque', 'Monégasque'],
  MN: ['Mongol', 'Mongole'],
  ME: ['Monténégrin', 'Monténégrine'],
  MZ: ['Mozambicain', 'Mozambicaine'],
  MM: ['Birman', 'Birmane'],
  NA: ['Namibien', 'Namibienne'],
  NR: ['Nauruan', 'Nauruane'],
  NP: ['Népalais', 'Népalaise'],
  NI: ['Nicaraguayen', 'Nicaraguayenne'],
  NE: ['Nigérien', 'Nigérienne'],
  NG: ['Nigérian', 'Nigériane'],
  NO: ['Norvégien', 'Norvégienne'],
  NZ: ['Néo-Zélandais', 'Néo-Zélandaise'],
  OM: ['Omanais', 'Omanaise'],
  UG: ['Ougandais', 'Ougandaise'],
  UZ: ['Ouzbek', 'Ouzbèke'],
  PK: ['Pakistanais', 'Pakistanaise'],
  PW: ['Palaosien', 'Palaosienne'],
  PS: ['Palestinien', 'Palestinienne'],
  PA: ['Panaméen', 'Panaméenne'],
  PG: ['Papouan-Néo-Guinéen', 'Papouane-Néo-Guinéenne'],
  PY: ['Paraguayen', 'Paraguayenne'],
  NL: ['Néerlandais', 'Néerlandaise'],
  PE: ['Péruvien', 'Péruvienne'],
  PH: ['Philippin', 'Philippine'],
  PL: ['Polonais', 'Polonaise'],
  PT: ['Portugais', 'Portugaise'],
  QA: ['Qatarien', 'Qatarienne'],
  CF: ['Centrafricain', 'Centrafricaine'],
  DO: ['Dominicain', 'Dominicaine'],
  CZ: ['Tchèque', 'Tchèque'],
  RO: ['Roumain', 'Roumaine'],
  GB: ['Britannique', 'Britannique'],
  RU: ['Russe', 'Russe'],
  RW: ['Rwandais', 'Rwandaise'],
  KN: ['Kittitien', 'Kittitienne'],
  SM: ['Saint-Marinais', 'Saint-Marinaise'],
  VC: ['Vincentais', 'Vincentaise'],
  LC: ['Saint-Lucien', 'Saint-Lucienne'],
  SB: ['Salomonais', 'Salomonaise'],
  WS: ['Samoan', 'Samoane'],
  ST: ['Santoméen', 'Santoméenne'],
  SN: ['Sénégalais', 'Sénégalaise'],
  RS: ['Serbe', 'Serbe'],
  SC: ['Seychellois', 'Seychelloise'],
  SL: ['Sierra-Léonais', 'Sierra-Léonaise'],
  SG: ['Singapourien', 'Singapourienne'],
  SK: ['Slovaque', 'Slovaque'],
  SI: ['Slovène', 'Slovène'],
  SO: ['Somalien', 'Somalienne'],
  SD: ['Soudanais', 'Soudanaise'],
  SS: ['Sud-Soudanais', 'Sud-Soudanaise'],
  LK: ['Sri-Lankais', 'Sri-Lankaise'],
  SE: ['Suédois', 'Suédoise'],
  CH: ['Suisse', 'Suisse'],
  SR: ['Surinamais', 'Surinamaise'],
  SY: ['Syrien', 'Syrienne'],
  TJ: ['Tadjik', 'Tadjike'],
  TZ: ['Tanzanien', 'Tanzanienne'],
  TD: ['Tchadien', 'Tchadienne'],
  TH: ['Thaïlandais', 'Thaïlandaise'],
  TL: ['Timorais', 'Timoraise'],
  TG: ['Togolais', 'Togolaise'],
  TO: ['Tongien', 'Tongienne'],
  TT: ['Trinidadien', 'Trinidadienne'],
  TN: ['Tunisien', 'Tunisienne'],
  TM: ['Turkmène', 'Turkmène'],
  TR: ['Turc', 'Turque'],
  TV: ['Tuvaluan', 'Tuvaluane'],
  UA: ['Ukrainien', 'Ukrainienne'],
  UY: ['Uruguayen', 'Uruguayenne'],
  VU: ['Vanuatuan', 'Vanuatuane'],
  VE: ['Vénézuélien', 'Vénézuélienne'],
  VN: ['Vietnamien', 'Vietnamienne'],
  YE: ['Yéménite', 'Yéménite'],
  ZM: ['Zambien', 'Zambienne'],
  ZW: ['Zimbabwéen', 'Zimbabwéenne'],
};

/**
 * Gentilé accordé au sexe. Quand le sexe n'est pas renseigné :
 * — gentilé invariable (Belge) : tel quel ;
 * — accord régulier (Sénégalais → Sénégalaise) : forme inclusive « Sénégalais·e » ;
 * — accord irrégulier (Grec → Grecque) : masculin, forme générique en usage
 *   administratif, parce que « Grec·que » ne se lit pas.
 *
 * Un code inconnu se rend tel quel plutôt que de disparaître : mieux vaut voir
 * « XX » et corriger que ne rien voir du tout.
 */
export function nationalityLabel(
  code: string | null | undefined,
  gender?: string | null,
): string | null {
  if (!code) return null;
  const pair = DEMONYMS[code.toUpperCase()];
  if (!pair) return code.toUpperCase();
  const [masculin, feminin] = pair;
  if (gender === 'female') return feminin;
  if (gender === 'male') return masculin;
  if (masculin === feminin) return masculin;
  // Seuls « -e » et « -ne » sont des accords réguliers : Sénégalais·e,
  // Malien·ne. « Grecque » commence pourtant par « Grec » — s'en tenir à
  // startsWith produisait « Grec·que », qui ne se lit pas.
  const suffixe = feminin.slice(masculin.length);
  const regulier = feminin.startsWith(masculin) && (suffixe === 'e' || suffixe === 'ne');
  return regulier ? `${masculin}·${suffixe}` : masculin;
}
