/**
 * Nationalités en français, par pays (ISO 3166-1 alpha-2).
 *
 * TOUJOURS AU FÉMININ, et ce n'est pas un oubli : le gentilé qualifie ici le
 * mot « nationalité », qui est féminin. On écrit « de nationalité malienne »
 * d'un homme comme d'une femme. Accorder au sexe de la personne serait une
 * faute — c'est la nationalité qu'on qualifie, pas l'individu.
 *
 * La valeur STOCKÉE reste le code pays : stable, indépendant de la langue. Mais
 * un dossier RH ne s'écrit pas « SN ».
 *
 * Partagée avec le serveur : l'attestation de travail et les descriptions de
 * demandes de correction en ont besoin autant que l'interface.
 */
export const NATIONALITY_LABELS: Record<string, string> = {
  AF: 'Afghane',
  ZA: 'Sud-Africaine',
  AL: 'Albanaise',
  DZ: 'Algérienne',
  DE: 'Allemande',
  AD: 'Andorrane',
  AO: 'Angolaise',
  AG: 'Antiguaise',
  SA: 'Saoudienne',
  AR: 'Argentine',
  AM: 'Arménienne',
  AU: 'Australienne',
  AT: 'Autrichienne',
  AZ: 'Azerbaïdjanaise',
  BS: 'Bahaméenne',
  BH: 'Bahreïnienne',
  BD: 'Bangladaise',
  BB: 'Barbadienne',
  BE: 'Belge',
  BZ: 'Bélizienne',
  BJ: 'Béninoise',
  BT: 'Bhoutanaise',
  BY: 'Biélorusse',
  BO: 'Bolivienne',
  BA: 'Bosnienne',
  BW: 'Botswanaise',
  BR: 'Brésilienne',
  BN: 'Brunéienne',
  BG: 'Bulgare',
  BF: 'Burkinabè',
  BI: 'Burundaise',
  KH: 'Cambodgienne',
  CM: 'Camerounaise',
  CA: 'Canadienne',
  CV: 'Cap-Verdienne',
  CL: 'Chilienne',
  CN: 'Chinoise',
  CY: 'Chypriote',
  CO: 'Colombienne',
  KM: 'Comorienne',
  CG: 'Congolaise',
  CD: 'Congolaise',
  KR: 'Sud-Coréenne',
  KP: 'Nord-Coréenne',
  CR: 'Costaricienne',
  CI: 'Ivoirienne',
  HR: 'Croate',
  CU: 'Cubaine',
  DK: 'Danoise',
  DJ: 'Djiboutienne',
  DM: 'Dominiquaise',
  EG: 'Égyptienne',
  AE: 'Émirienne',
  EC: 'Équatorienne',
  ER: 'Érythréenne',
  ES: 'Espagnole',
  EE: 'Estonienne',
  SZ: 'Swazie',
  US: 'Américaine',
  ET: 'Éthiopienne',
  FJ: 'Fidjienne',
  FI: 'Finlandaise',
  FR: 'Française',
  GA: 'Gabonaise',
  GM: 'Gambienne',
  GE: 'Géorgienne',
  GH: 'Ghanéenne',
  GR: 'Grecque',
  GD: 'Grenadienne',
  GT: 'Guatémaltèque',
  GN: 'Guinéenne',
  GW: 'Bissau-Guinéenne',
  GQ: 'Équato-Guinéenne',
  GY: 'Guyanienne',
  HT: 'Haïtienne',
  HN: 'Hondurienne',
  HU: 'Hongroise',
  IN: 'Indienne',
  ID: 'Indonésienne',
  IQ: 'Irakienne',
  IR: 'Iranienne',
  IE: 'Irlandaise',
  IS: 'Islandaise',
  IL: 'Israélienne',
  IT: 'Italienne',
  JM: 'Jamaïcaine',
  JP: 'Japonaise',
  JO: 'Jordanienne',
  KZ: 'Kazakhe',
  KE: 'Kényane',
  KG: 'Kirghize',
  KI: 'Kiribatienne',
  KW: 'Koweïtienne',
  LA: 'Laotienne',
  LS: 'Lesothane',
  LV: 'Lettone',
  LB: 'Libanaise',
  LR: 'Libérienne',
  LY: 'Libyenne',
  LI: 'Liechtensteinoise',
  LT: 'Lituanienne',
  LU: 'Luxembourgeoise',
  MK: 'Macédonienne',
  MG: 'Malgache',
  MY: 'Malaisienne',
  MW: 'Malawienne',
  MV: 'Maldivienne',
  ML: 'Malienne',
  MT: 'Maltaise',
  MA: 'Marocaine',
  MH: 'Marshallaise',
  MU: 'Mauricienne',
  MR: 'Mauritanienne',
  MX: 'Mexicaine',
  FM: 'Micronésienne',
  MD: 'Moldave',
  MC: 'Monégasque',
  MN: 'Mongole',
  ME: 'Monténégrine',
  MZ: 'Mozambicaine',
  MM: 'Birmane',
  NA: 'Namibienne',
  NR: 'Nauruane',
  NP: 'Népalaise',
  NI: 'Nicaraguayenne',
  NE: 'Nigérienne',
  NG: 'Nigériane',
  NO: 'Norvégienne',
  NZ: 'Néo-Zélandaise',
  OM: 'Omanaise',
  UG: 'Ougandaise',
  UZ: 'Ouzbèke',
  PK: 'Pakistanaise',
  PW: 'Palaosienne',
  PS: 'Palestinienne',
  PA: 'Panaméenne',
  PG: 'Papouane-Néo-Guinéenne',
  PY: 'Paraguayenne',
  NL: 'Néerlandaise',
  PE: 'Péruvienne',
  PH: 'Philippine',
  PL: 'Polonaise',
  PT: 'Portugaise',
  QA: 'Qatarienne',
  CF: 'Centrafricaine',
  DO: 'Dominicaine',
  CZ: 'Tchèque',
  RO: 'Roumaine',
  GB: 'Britannique',
  RU: 'Russe',
  RW: 'Rwandaise',
  KN: 'Kittitienne',
  SM: 'Saint-Marinaise',
  VC: 'Vincentaise',
  LC: 'Saint-Lucienne',
  SB: 'Salomonaise',
  WS: 'Samoane',
  ST: 'Santoméenne',
  SN: 'Sénégalaise',
  RS: 'Serbe',
  SC: 'Seychelloise',
  SL: 'Sierra-Léonaise',
  SG: 'Singapourienne',
  SK: 'Slovaque',
  SI: 'Slovène',
  SO: 'Somalienne',
  SD: 'Soudanaise',
  SS: 'Sud-Soudanaise',
  LK: 'Sri-Lankaise',
  SE: 'Suédoise',
  CH: 'Suisse',
  SR: 'Surinamaise',
  SY: 'Syrienne',
  TJ: 'Tadjike',
  TZ: 'Tanzanienne',
  TD: 'Tchadienne',
  TH: 'Thaïlandaise',
  TL: 'Timoraise',
  TG: 'Togolaise',
  TO: 'Tongienne',
  TT: 'Trinidadienne',
  TN: 'Tunisienne',
  TM: 'Turkmène',
  TR: 'Turque',
  TV: 'Tuvaluane',
  UA: 'Ukrainienne',
  UY: 'Uruguayenne',
  VU: 'Vanuatuane',
  VE: 'Vénézuélienne',
  VN: 'Vietnamienne',
  YE: 'Yéménite',
  ZM: 'Zambienne',
  ZW: 'Zimbabwéenne',
};

/**
 * Nationalité lisible à partir du code pays. Aucun paramètre de sexe : voir
 * ci-dessus, l'accord se fait avec « nationalité », pas avec la personne.
 *
 * Un code inconnu se rend tel quel plutôt que de disparaître : mieux vaut voir
 * « XX » et corriger que ne rien voir du tout.
 */
export function nationalityLabel(code: string | null | undefined): string | null {
  if (!code) return null;
  return NATIONALITY_LABELS[code.toUpperCase()] ?? code.toUpperCase();
}
